### ISSUE TITLE
How can I do the setup?

### ISSUE THREAD

**Issue by danielp3011** [GregHilston/Google-Trends-Scraper#3]
I get the following error: "WebDriverException: Message: 'geckodriver' executable needs to be in PATH. "

**Comment by GregHilston** [comment]
Hey @danielp3011 

How familiar are you with Python and Selenium?

Rather then reinvent the wheel with documentation, take a look at this SO answer and see if the author's steps help you: https://stackoverflow.com/a/40208762/1983957

Let me know if I can provide any further assistance, but I'll likely close this, if I don't hear from you, as its not related to this project.

**Comment by danielp3011** [comment]
Thanks for your answer.
I used Selenium with Python once, I installed geckodriver in that context but then made it to work with chromedriver.
Thanks for the link, I'll try that. Do I understand it right, that the problem lies in the configuration of the Selenium package and not in the configuration of Google-Trends-Scraper?

**Comment by GregHilston** [comment]
Correct!

**Comment by GregHilston** [comment]
Closing. Please create a new issue if you have a problem related to this project!

Happy coding!
